### ISSUE TITLE
Adapter crashes if no fritzbox at ip

### ISSUE THREAD

**Issue by Garfonso** [afuerhoff/ioBroker.fb-checkpresence#9]
**Describe the bug**  
The adapter starts with a wrong configured IP, so there is no FB at the IP it tries to reach, then the adapter crashes with uncaught error messages.

**To Reproduce**  
1. Install adapter & create instance
2. Have your Fritzbox not running on default of 192.168.178.1 but something else ;-)
4. See errors in log fie

**Expected behavior**  
The adapter should catch the errors and print a human readable error in the log indicating it did not find a fritzbox at the specified IP and either exit cleanly or do nothing at all. Crashing the adapter will lead to ugly errors, does not make clear what the issue is and will let js-controller restart the adapter over and over.

**Screenshots & Logfiles**  
```2020-02-13 11:23:59.514  - info: host.Server instance system.adapter.fb-checkpresence.0 started with pid 4290
2020-02-13 11:24:00.236  - info: fb-checkpresence.0 (4290) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v10.18.0
2020-02-13 11:24:00.268  - info: fb-checkpresence.0 (4290) start fb-checkpresence: ip-address: 192.168.178.1 polling interval: 1 Min.
2020-02-13 11:24:11.620  - error: fb-checkpresence.0 (4290) onMessage: Cannot read property 'length' of undefined
2020-02-13 11:26:09.930  - error: fb-checkpresence.0 (4290) uncaught exception: Cannot read property 'search' of undefined
2020-02-13 11:26:09.931  - error: fb-checkpresence.0 (4290) TypeError: Cannot read property 'search' of undefined
    at /opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:37:57
    at Parser.<anonymous> (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:308:18)
    at Parser.exports.Parser.Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:327:16)
    at Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:369:19)
    at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:36:17)
    at self.callback (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/request/request.js:185:22)
    at Request.onRequestError (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/request/request.js:877:8)
2020-02-13 11:26:09.932  - info: fb-checkpresence.0 (4290) cleaned everything up...
2020-02-13 11:26:09.933  - error: fb-checkpresence.0 (4290) onReady: connect ETIMEDOUT 192.168.178.1:49000
2020-02-13 11:26:09.937  - info: fb-checkpresence.0 (4290) terminating
2020-02-13 11:26:09.938  - info: fb-checkpresence.0 (4290) Terminated (NO_ERROR): Without reason
2020-02-13 11:26:11.254  - error: host.Server Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:37:57
2020-02-13 11:26:11.254  - error: host.Server Caught by controller[0]:     at Parser.<anonymous> (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:308:18)
2020-02-13 11:26:11.254  - error: host.Server Caught by controller[0]:     at Parser.exports.Parser.Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:327:16)
2020-02-13 11:26:11.254  - error: host.Server Caught by controller[0]:     at Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:5:59)
2020-02-13 11:26:11.254  - error: host.Server Caught by controller[0]:     at exports.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:369:19)
2020-02-13 11:26:11.254  - error: host.Server Caught by controller[0]:     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:36:17)
2020-02-13 11:26:11.255  - error: host.Server Caught by controller[0]:     at self.callback (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/request/request.js:185:22)
2020-02-13 11:26:11.255  - error: host.Server Caught by controller[0]:     at Request.onRequestError (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/request/request.js:877:8)
2020-02-13 11:26:11.255  - info: host.Server instance system.adapter.fb-checkpresence.0 terminated with code 0 (NO_ERROR)
2020-02-13 11:26:11.255  - info: host.Server Restart adapter system.adapter.fb-checkpresence.0 because enabled
2020-02-13 11:26:41.271  - info: host.Server instance system.adapter.fb-checkpresence.0 started with pid 12590
2020-02-13 11:26:42.369  - info: fb-checkpresence.0 (12590) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v10.18.0
2020-02-13 11:26:42.394  - info: fb-checkpresence.0 (12590) start fb-checkpresence: ip-address: 192.168.178.1 polling interval: 1 Min.
2020-02-13 11:28:51.728  - error: fb-checkpresence.0 (12590) uncaught exception: Cannot read property 'search' of undefined
2020-02-13 11:28:51.729  - error: fb-checkpresence.0 (12590) TypeError: Cannot read property 'search' of undefined
    at /opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:37:57
    at Parser.<anonymous> (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:308:18)
    at Parser.exports.Parser.Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:327:16)
    at Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:369:19)
    at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:36:17)
    at self.callback (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/request/request.js:185:22)
    at Request.onRequestError (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/request/request.js:877:8)
2020-02-13 11:28:51.729  - info: fb-checkpresence.0 (12590) cleaned everything up...
2020-02-13 11:28:51.730  - error: fb-checkpresence.0 (12590) onReady: connect ETIMEDOUT 192.168.178.1:49000
2020-02-13 11:28:51.733  - info: fb-checkpresence.0 (12590) terminating
2020-02-13 11:28:51.734  - info: fb-checkpresence.0 (12590) Terminated (NO_ERROR): Without reason
2020-02-13 11:28:52.400  - error: host.Server Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:37:57
2020-02-13 11:28:52.401  - error: host.Server Caught by controller[0]:     at Parser.<anonymous> (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:308:18)
2020-02-13 11:28:52.401  - error: host.Server Caught by controller[0]:     at Parser.exports.Parser.Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:327:16)
2020-02-13 11:28:52.402  - error: host.Server Caught by controller[0]:     at Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:5:59)
2020-02-13 11:28:52.402  - error: host.Server Caught by controller[0]:     at exports.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:369:19)
2020-02-13 11:28:52.402  - error: host.Server Caught by controller[0]:     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:36:17)
2020-02-13 11:28:52.402  - error: host.Server Caught by controller[0]:     at self.callback (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/request/request.js:185:22)
2020-02-13 11:28:52.402  - error: host.Server Caught by controller[0]:     at Request.onRequestError (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/request/request.js:877:8)
2020-02-13 11:28:52.402  - info: host.Server instance system.adapter.fb-checkpresence.0 terminated with code 0 (NO_ERROR)
2020-02-13 11:28:52.402  - info: host.Server Restart adapter system.adapter.fb-checkpresence.0 because enabled
2020-02-13 11:29:03.581  - info: host.Server instance system.adapter.fb-checkpresence.0 started with pid 19959
```

**Versions:**  
 - Adapter version: 0.2.2
 - JS-Controller version: 2.2.8
 - Node version: 10.18.0
 - Operating system: linux / ubuntu

Works fine after I changed the IP. Thanks. :-)

**Comment by afuerhoff** [comment]
Hi Garfonso, have you installed the latest version from github? I have changed it for some days. The version is the old one.

**Comment by Garfonso** [comment]
Hi,

sorry, now this was the version from latest. U just checked with github-Version. I do not get a crash now but also do not see an error message in the log (or was not patient enough for a timeout?). For a wrong IP where someone answers, I get an error message and indicator turns yellow, so all fine.

Sorry for the inconviniece,
Garfonso
